### ISSUE TITLE
Hacer pantalla de Registro

### ISSUE THREAD

**Issue by ShermanPI** [AutumnLeaf742002/santuario#6]
Pantalla de figma a maquetar: https://www.figma.com/file/lEUKiPm4rWpenDdcLn5NCn/Asilo-de-Personas-Mayores?type=design&node-id=54-36&mode=design&t=KCAcTwoXY1oHTPji-4

- El usuario puede ver la pantalla de registro luego de darle al botón que lleva al formulario
- Luego de darle a acceder el usuario será redireccionado hacia la pantalla de inicio de sesión

**Comment by warren-dev0** [comment]
resuelta
